import { Col, Row } from "antd";
import ApplePrivacyStyle from "./style";

export default function ApplePrivacy() {
    window.scrollTo(0,0);
    return(
        <ApplePrivacyStyle>
            <div className="wrapper">
                <div className="intro">
                    <Row>
                        <Col span={24}>
                            <h1>Apple TV App & Privacy</h1>
                            <p className="sub">Your playback, searches, purchases, and device trust score are used to personalize your experience, improve the service, send you notifications, and prevent fraud. Your device serial number may be used to check eligibility for offers.</p>
                            <p className="main">The Apple TV app is designed to protect your information and enable you to choose what you share.</p>
                            <img src="https://www.apple.com/legal/images/icon_dataprivacy_2x.png" />
                        </Col>
                    </Row>
                </div>
                <div className="info">
                    <Row>
                        <Col span={24}>
                            <div className="point">
                                <svg xmlns="http://www.w3.org/2000/svg" height="6" width="6" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                <p>The Apple TV app brings your favorite TV shows and movies all into one place and recommends others you might enjoy.</p>
                            </div>
                            <div className="point">
                            <svg xmlns="http://www.w3.org/2000/svg" height="14" width="14" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                <p>Apple collects information about your purchases, downloads, activity in the Apple TV app, the content you watch, and where you watch it in the Apple TV app and in connected apps on any of your supported devices. We use this information to provide the service and to improve the Apple TV app for you and others.</p>
                            </div>
                            <div className="point">
                                <svg xmlns="http://www.w3.org/2000/svg" height="14" width="14" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                <p>We also collect information about your purchases, downloads, activity in the Apple TV app, the content you watch, and where you watch it to tailor features and offer personalized recommendations and to send you notifications. You can opt out of the use of data for this purpose, as described below.</p>
                            </div>
                            <div className="point">
                                <svg xmlns="http://www.w3.org/2000/svg" height="13" width="13" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                <p>We use information about the movies and TV shows you purchase and download to offer advertising to ensure that Ads in the App Store, Apple News, and Stocks, where available, are relevant to you. You have choices with respect to this advertising, as described below.</p>
                            </div>
                            <div className="point">
                                <svg xmlns="http://www.w3.org/2000/svg" height="18" width="18" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                <p>To help identify and prevent fraud, information about how you use your device, including the approximate number of phone calls or emails you send and receive, will be used to compute a device trust score when you attempt a purchase. The submissions are designed so Apple cannot learn the real values on your device. The scores are stored for a fixed time on our servers.</p>
                            </div>
                            <div className="exp">
                                <p>Apple TV allows you to watch your favorite TV shows and movies all in one place. You can watch content you have rented or purchased from Apple. If available, you can also access content through Apple TV+, Apple TV channels, and your connected third-party video apps. You can access all of this content through the Apple TV app across supported devices that are signed in to the same Apple ID.</p>
                                <p>Providing the Apple TV App</p>
                                <p>We use your personal data to provide the services and features in the Apple TV app. This information includes your account and payment information, which you can access and change in Settings.</p>
                                <p>Apple collects information about what you purchase and what you’re watching in the Apple TV app on any supported devices signed in to the same Apple ID. Apple stores this information associated with your Apple ID so we can display what you’re watching across your supported devices. When you sign in to third-party apps, information about whether you have subscribed to those services is used to display content available to you. If you grant permission for a third-party app to be connected to the Apple TV app, Apple will collect and store information about what you watch from that app on any of your supported devices, as well as your subscription status. Apple apps with supported content, such as Apple Music, will be automatically connected when you start using the Apple TV app.</p>
                                <p>Information about what you’re watching will include what content you’re playing, when you played it, the device you played it from, and where in the content you paused or stopped watching. We also collect a detailed history of all playback activity for Apple TV channels and Apple TV+.</p>
                                <p>If you allow the Apple TV app to access your location, your location will be used to determine what’s available in your region, including local content like live games, events, and news. Some content includes geographically relevant ads.</p>
                                <p>Improving the Apple TV App</p>
                                <p>Apple collects information about your usage of the Apple TV app and your account, including the features you use (for example, Up Next or Library), items you search for, your interactions with notifications, content pages you browse or view, information on errors or crashes within the app, and your billing zip code. We use this information, approximate location information that does not identify you, and information about what you watch to help improve and optimize the service for you and others. We also collect information about your device such as the type of device, the channel through which your device was obtained, the version of your operating system, and the amount of free space on your device. We may use this information to assess whether requested content can be downloaded, to understand general trends in device usage and storage, and whether your device is connected by Wi-Fi or cellular. For example, knowing the free space on your device allowed us to build the feature that lets you buy a movie on your iPhone without downloading it at purchase. If you use SharePlay to watch content with other users, the Apple TV app will collect that you watched that content during a SharePlay session and the number of devices that participated in the session, but does not collect any information to identify the participants of a SharePlay session.</p>
                                <p>Personalizing the Apple TV App</p>
                                <p>We personalize the Apple TV app to help you discover the content that’s most relevant to you. For example, we recommend movies that we think will be of interest to you based on movies you’ve previously watched. To provide personalization, we use information including what you watch, your purchases, subscriptions, downloads, browsing, and other activities in the Apple TV app, as well as information from your account such as your age.</p>
                                <p>If you do not want Apple to use information about what you watch on this device in the Apple TV app for personalization on all devices that support the Apple TV app, you can turn off Use Play History in Settings. On your iOS or iPadOS device, go to Settings > TV > Use Play History. On tvOS, go to Settings > Apps > TV > Use Play History.</p>
                                <p>You can turn off personalization features in the App Store, Apple Books, iTunes Store, Apple TV, Apple Podcasts, and for subscriptions from Apple by turning off Personalized Recommendations for your Apple ID. On your iOS or iPadOS device, go to Settings > [your name] > Media & Purchases > View Account, then tap to turn off Personalized Recommendations. In the Apple TV app on Mac, go to Account > Account Settings > Settings.</p>
                                <p>Communicating with You</p>
                                <p>Apple may use information about your account, such as the Apple products you own, your subscriptions to Apple services, and your billing zip code, to send you communications about the Apple TV app and other Apple products, services, and offers that may be of interest to you, including Apple One. Details about your device, such as its device serial number, may be used to check eligibility for offers. If you are in a Family Sharing group, Apple may send you communications about products, services, and offers available to you through Family Sharing. If you purchase an Apple One subscription, we may send you emails and push notifications about the features of each of the services for which you have subscribed. Apple may also use information about your activity within the Apple TV app to send you emails and push notifications about new features, content, and offers available in the Apple TV app. You can change your email preferences and opt out of receiving these emails by going to <a className="link" href="#">appleid.apple.com</a>. To update notification preferences on your iOS or iPadOS device, go to Settings > Notifications > TV.</p>
                                <p>Advertising</p>
                                <p>In the Apple TV app, if you allow the Apple TV app to access your location, your location may be used to serve geographically relevant ads.</p>
                                <p>For other apps such as the App Store, Apple News, and Stocks, if the Personalized Ads setting is turned on, Apple’s advertising platform may use your information, including information about the movies and TV shows you purchase from Apple, to serve ads in those apps that are more relevant to you.</p>
                                <p>If you do not want to receive ads targeted to your interests from Apple’s advertising platform, you can choose to turn off Personalized Ads. Turning off Personalized Ads will prevent Apple from using your information for ad targeting. It may not decrease the number of ads you receive, but the ads may be less relevant to you.</p>
                                <p>You can change your Personalized Ads settings by going to Settings > Privacy & Security > Apple Advertising.</p>
                                <p>Learn more about Apple Advertising & Privacy at <a className="link" href="#">www.apple.com/legal/privacy/data/en/apple-advertising</a>.</p>
                                <p>Learn about how to opt out of personalized ads on the App Store, Apple News, and Stocks at <a className="link" href="#">support.apple.com/kb/HT202074</a>.</p>
                                <p>Sharing with Third Parties</p>
                                <p>We provide some non-personal data to our advertisers and strategic partners that work with Apple to provide our products and services, help Apple market to customers, and sell ads on Apple’s behalf to display on the App Store and Apple News and Stocks. For example, we may share non-personal data about your transactions and viewing activity, as well as aggregated user demographics such as age group, gender (which may be inferred from information such as your name and salutation in your Apple ID account), and region, to Apple TV strategic partners, such as content owners, so that they can measure the performance of their creative work, meet royalty and accounting requirements, and improve their associated products and services.</p>
                                <p>If your mobile network provider offers Apple TV+ subscriptions and free trials, Apple may check your phone number to determine if you are eligible through a mobile network provider partner. If you sign up for an Apple TV+ subscription or free trial through your mobile network provider or another Apple partner, Apple will use your phone number or a unique account identifier shared by the partner to identify your account and to let the mobile network provider or other partner know that you have activated your subscription. We will use the phone number or unique identifier associated with your subscription to verify your account at sign in and to connect your Apple TV+ subscription with your account.</p>
                                <p>If you sign in to the Apple TV app on a non-Apple device, Apple may share information with the platform provider to enable the app to function, so that content from your Apple TV subscriptions appears on the platform, and to support platform features such as providing search results and personalized recommendations. This may include information about whether you have opened the Apple TV app and, where available, whether you have subscribed to Apple TV+ and Apple TV channels. You can choose to stop sharing your subscription information in the Apple TV app settings on your non-Apple device, although doing so may limit the ways that Apple TV content appears on the platform.</p>
                                <p>On supported non-Apple devices, you can choose whether to share what you watch, buy, or rent in the Apple TV app, including Apple TV+, Apple TV channels, and other content (where available) with the provider of your third-party platform. Your platform provider may use this information to enable platform features such as displaying the shows you have in progress and personalized recommendations. You can turn this off by going to the Apple TV app settings on your non-Apple device. On some devices, this may direct you to the platform’s settings.</p>
                                <p>If you choose to sign in to the Apple TV app on a non-Apple device, you should review the terms, privacy policies, and practices of the platform’s provider to understand what data it collects, uses, and shares.</p>
                                <p>Retention</p>
                                <p>We retain personal data associated with your purchases, downloads, and viewing activity on the Apple TV app for different lengths of time depending on business need, contractual obligations, and legal requirements. For purchases and downloads, that often requires at least a 10-year retention period, but in regions such as China that period can be 30 years. We also retain a record of your purchase and downloads of content for at least as long as you have an account with us to allow you to download that content in line with our applicable terms. We retain other information such as browsing activity and searches for up to two years. Some information, such as transactions but not your stored card details may be retained as business records even after you close your account or stop using the Apple TV app.</p>
                                <p>When you use a payment card, Apple may retain and automatically update your card number and billing information for future purchases, recurring transactions, or other uses you authorize. Apple may obtain this information from your financial institution or payment network, and also use it for fraud prevention and verification.</p>
                                <p>Clear Play History</p>
                                <p>You can clear your play history in the Apple TV app in Settings. In the Apple TV app on your iOS or iPadOS device, go to Account > Clear Play History. On tvOS, go to Settings > Apps > TV > Clear Play History. This will remove all TV shows and movies from your Up Next queue and disassociate any past playback history from your account. This will apply to your play data that is held and used by Apple on devices that use the same Apple ID. If you use a non-Apple device and have chosen to share what you watch with that platform’s provider, clearing your play history will not affect the play data that is stored by the platform’s provider. You should review the terms, privacy policies, and practices of the platform’s provider to understand whether you can delete the data stored by that provider.</p>
                                <p>You can remove individual items from your Up Next queue by long-pressing the episode and selecting Remove from Up Next. In the same menu, if you select Remove from Recently Watched, that will also remove the episode from being used to generate personalized recommendations. However, Apple will retain records of play history from Apple TV channels and Apple TV+ for reporting and royalty requirements.</p>
                                <p>Third-Party Connected Apps</p>
                                <p>You must grant permission for your participating third-party apps to be connected to the Apple TV app to begin sharing what you watch from those apps with Apple. When you set up the Apple TV app, you may be asked to grant permission for multiple applications at one time. Some of the apps may be apps that you do not yet have installed on that device, and your preferences will be applied if they are installed later. Whether or not you grant permission, you will be able to change your preferences for each app in Settings.</p>
                                <p>If at any time you decide you no longer want one of your third-party apps to be connected to the Apple TV app, you may disconnect that app from the Apple TV app and Apple will stop collecting your play data from that third-party app. In the Apple TV app on your iOS or iPadOS device, go to Account > Connected Apps, select the third-party app and turn it off. On tvOS, go to Settings > Apps > TV > Connect to TV, select the third-party app and turn it off. When removing a third-party app from the Apple TV app, you may also choose to delete all play data information Apple has collected about content you’ve watched from that app by choosing the Remove and Clear Play History option. At any time, you may also choose to delete all of your play data information Apple has collected about all third-party content you watch in the Apple TV app by clearing your play history as described above. Clearing your play history in any of these described instances only clears your third-party app play data that is held and used by Apple for the Apple TV app. It does not affect any play data that is held separately by the third-party app provider (for example, within their own app or on their servers).</p>
                                <p>You should also review the terms, privacy policies, and practices of your participating third-party apps to understand how they use and share your play data and related information.</p>
                                <p>Group Recommendations</p>
                                <p>If you choose to enable Group Recommendations on an Apple TV device, information about what you watch will be used to make group recommendations with any combination of opted-in users on the same Apple TV. If a child account is in the group, recommendations for children will be included, but their watch history will not be used. You can turn off Group Recommendations for your account at any time by going to Settings > Users and Accounts, selecting your profile, then selecting For All of You.</p>
                                <p>Preventing Fraud and Other Malicious Activity</p>
                                <p>We also collect personal data to prevent fraud and other malicious activity in the Apple TV app. This information includes device information, such as device type and software version, location information if available, download and purchase history, and other interactions with the Apple TV app.</p>
                                <p>We also may compute a device trust score on your device when you attempt a purchase, using information about how you use your device, including the approximate number of phone calls or emails you send and receive. The submission is designed so Apple cannot learn the underlying values on your device. The score is stored for a fixed time on our servers.</p>
                                <p>Applicable Legal Basis for Processing Personal Data</p>
                                <p>We process your personal data in the Apple TV app generally for performance of your contract with Apple, as necessary for providing the service, and to comply with our legal obligations. Where consent is the appropriate legal basis, we seek it in accordance with applicable local law.</p>
                                <p>Where applicable local law provides, we process personal data as necessary for purposes of our legitimate interests or those of a third party in order to:</p>
                                <div className="point">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="6" width="6" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                    <p>Display available and relevant content to you, including from third-party services</p>
                                </div>
                                <div className="point">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="11" width="11" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                    <p>Check eligibility for offers, help to improve and optimize the service for you and others, and send you communications about the Apple TV app and other Apple products, services, and offers that may be of interest to you</p>
                                </div>
                                <div className="point">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="6" width="6" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                    <p>Prevent fraud and other malicious activity</p>
                                </div>
                                <p>The data used includes:</p>
                                <div className="point">
                                <svg xmlns="http://www.w3.org/2000/svg" height="14" width="14" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                    <p>Your use of the Apple TV app including features you use (for example, Up Next or Library), items you search for, your interactions with notifications, content pages you browse or view, what you watch, purchase, subscribe to, and download, and information about errors or crashes within the app</p>
                                </div><div className="point">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="6" width="6" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                    <p>Details about your device and account</p>
                                </div><div className="point">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="6" width="6" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                    <p>The device trust score</p>
                                </div><div className="point">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="6" width="6" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/></svg>
                                    <p>Your location</p>
                                </div>
                                <p>At all times, information collected by Apple will be treated in accordance with Apple’s Privacy Policy, which can be found at <a className="link" href="#">www.apple.com/privacy</a></p>
                                <p>Published Date: December 11, 2023</p>
                            </div>
                        </Col>
                    </Row>
                </div>
            </div>
        </ApplePrivacyStyle>
    );
}